### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by aminraeisi** [josiasmontag/laravel-redis-mock#1]
More easier can be just add the follwing to your `phpunit.xml` file.
`<env name="REDIS_CLIENT" value="mock"/>`
Because then you can use redis when you are viewing your application (using homestead for example) and in testing it will be mocked as expected.

Thank for the package!

**Comment by josiasmontag** [comment]
Setting `REDIES_CLIENT` in `.env.testing` has the same effect, because phpunit.xml normally contains:
`<env name="APP_ENV" value="testing"/>`

Thanks for the hint though.
