### ISSUE TITLE
Redis::hmset( ) behaviour

### ISSUE THREAD

**Issue by tomlankhorst** [josiasmontag/laravel-redis-mock#3]
In Laravel, using the `predis` backend, `hmset` would work as follows: 
```
Redis::command('hmset', [
  'somekey', 
  'property',
  'value'
]);
```
which leads to an exception when using the mock: 
`Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /application/vendor/m6web/redis-mock/src/M6Web/Component/RedisMock/RedisMock.php:638)`

whereas the Redis mock expects the property and value to be passed as an associative array.

```
Redis::command('hmset', [
  'somekey', 
  ['property' => 'value']
]);
```
in which case Laravel produces an exception:
`ErrorException  : strlen() expects parameter 1 to be string, array given at /application/vendor/predis/predis/src/Connection/StreamConnection.php:390`

This seems to be inconsistent...

**Comment by josiasmontag** [comment]
Is there a reason why you are using ``Redis::command()``? Did you try the same with ``Redis::hmset()``?

**Comment by tomlankhorst** [comment]
Yes, I did.

This works with the mock, but not with Laravel & phpredis:

```
Redis::hmset(
   'somekey', 
  ['property' => 'value']
]);
```
`ErrorException  : strlen() expects parameter 1 to be string, array given at /application/vendor/predis/predis/src/Connection/StreamConnection.php:390`

Imho, it would be nice if `phpredis` would just 'expand' arrays in the commands as they occur.
It seems like some difference in behaviour between phpredis and PHP's Redis extension.

**Comment by josiasmontag** [comment]
According to predis documentation, it should work: https://github.com/nrk/predis/blob/master/FAQ.md#how-predis-abstracts-redis-commands

So I don't think there is any issue here, the problem seems to be somewhere else.
