### ISSUE TITLE
zrank, zrevrank error

### ISSUE THREAD

**Issue by socoolbear** [josiasmontag/laravel-redis-mock#8]
The functions operate in the opposite way. (on testing)
Because of this issue , ...

```

       if (Config::get('app.env') === 'testing') {
            return $connection->zRank($key, $id);
        }

        return $tconnection->zRevRank($key, $id);

```

ref :
    https://github.com/M6Web/RedisMock/pull/84

**Comment by josiasmontag** [comment]
Please open an issue on the M6Web/RedisMock repo
