### ISSUE TITLE
New redismock library

### ISSUE THREAD

**Issue by sevrugin** [josiasmontag/laravel-redis-mock#9]
Hi! Is it possible to upgrade to `m6web/redis-mock` library v5+ ?
Thanks!

**Comment by sevrugin** [comment]
@josiasmontag @tomlankhorst ? ^^

**Comment by sevrugin** [comment]
@tomlankhorst I have created a pull request. Can you have a look?

**Comment by sevrugin** [comment]
@tomlankhorst can you please add a new release tag?

**Comment by tomlankhorst** [comment]
@sevrugin , @josiasmontag is the maintainer of this repo :)

**Comment by josiasmontag** [comment]
Release will follow in the coming weeks with Laravel 9. 
In meantime you can use it via the `dev-master` version in your composer.json.
